//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.4.0.0 (NJsonSchema v11.3.2.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* tslint:disable */
/* eslint-disable */
// ReSharper disable InconsistentNaming

export interface ISwaggerSdk {

    /**
     * @param pageIndex (optional) 
     * @param pageSize (optional) 
     * @return OK
     */
    listCompaniesOffset(pageIndex?: number | undefined, pageSize?: number | undefined): Promise<CompaniesResponseOffset>;

    /**
     * @param pageSize (optional) 
     * @param cursor (optional) 
     * @param search (optional) 
     * @param sortBy (optional) 
     * @param sortDirection (optional) 
     * @param isDownloadAll (optional) 
     * @return OK
     */
    listCompaniesCursor(pageSize?: number | undefined, cursor?: string | undefined, search?: string | undefined, sortBy?: string | undefined, sortDirection?: string | undefined, isDownloadAll?: boolean | undefined): Promise<CompaniesResponseCursor>;

    /**
     * @return OK
     */
    deleteCompany(id: number): Promise<void>;

    /**
     * Applies a JSON Patch to a company.
     * @param body (optional) 
     * @return OK
     */
    patchCompany(id: number, body?: Operation[] | undefined): Promise<CompanyDto>;

    /**
     * @return OK
     */
    getCompany(id: number): Promise<CompanyDto>;

    /**
     * @return OK
     */
    getCompanyContacts(companyId: number): Promise<ContactDto[]>;

    /**
     * @param body (optional) 
     * @return OK
     */
    createCompanyContact(companyId: number, body?: CreateContactDto | undefined): Promise<ContactDto>;

    /**
     * @return OK
     */
    deleteContact(companyId: number, id: number): Promise<void>;

    /**
     * @param body (optional) 
     * @return OK
     */
    updateContact(companyId: number, id: number, body?: ContactDto | undefined): Promise<void>;
}

export class SwaggerSdk implements ISwaggerSdk {
    private http: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> };
    private baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(baseUrl?: string, http?: { fetch(url: RequestInfo, init?: RequestInit): Promise<Response> }) {
        this.http = http ? http : window as any;
        this.baseUrl = baseUrl ?? "";
    }

    /**
     * @param pageIndex (optional) 
     * @param pageSize (optional) 
     * @return OK
     */
    listCompaniesOffset(pageIndex?: number | undefined, pageSize?: number | undefined, signal?: AbortSignal): Promise<CompaniesResponseOffset> {
        let url_ = this.baseUrl + "/api/v2/companies/offset-based?";
        if (pageIndex === null)
            throw new Error("The parameter 'pageIndex' cannot be null.");
        else if (pageIndex !== undefined)
            url_ += "pageIndex=" + encodeURIComponent("" + pageIndex) + "&";
        if (pageSize === null)
            throw new Error("The parameter 'pageSize' cannot be null.");
        else if (pageSize !== undefined)
            url_ += "pageSize=" + encodeURIComponent("" + pageSize) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            signal,
            headers: {
                "Accept": "text/plain"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processListCompaniesOffset(_response);
        });
    }

    protected processListCompaniesOffset(response: Response): Promise<CompaniesResponseOffset> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = CompaniesResponseOffset.fromJS(resultData200);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<CompaniesResponseOffset>(null as any);
    }

    /**
     * @param pageSize (optional) 
     * @param cursor (optional) 
     * @param search (optional) 
     * @param sortBy (optional) 
     * @param sortDirection (optional) 
     * @param isDownloadAll (optional) 
     * @return OK
     */
    listCompaniesCursor(pageSize?: number | undefined, cursor?: string | undefined, search?: string | undefined, sortBy?: string | undefined, sortDirection?: string | undefined, isDownloadAll?: boolean | undefined, signal?: AbortSignal): Promise<CompaniesResponseCursor> {
        let url_ = this.baseUrl + "/api/v2/companies?";
        if (pageSize === null)
            throw new Error("The parameter 'pageSize' cannot be null.");
        else if (pageSize !== undefined)
            url_ += "pageSize=" + encodeURIComponent("" + pageSize) + "&";
        if (cursor === null)
            throw new Error("The parameter 'cursor' cannot be null.");
        else if (cursor !== undefined)
            url_ += "cursor=" + encodeURIComponent("" + cursor) + "&";
        if (search === null)
            throw new Error("The parameter 'search' cannot be null.");
        else if (search !== undefined)
            url_ += "search=" + encodeURIComponent("" + search) + "&";
        if (sortBy === null)
            throw new Error("The parameter 'sortBy' cannot be null.");
        else if (sortBy !== undefined)
            url_ += "sortBy=" + encodeURIComponent("" + sortBy) + "&";
        if (sortDirection === null)
            throw new Error("The parameter 'sortDirection' cannot be null.");
        else if (sortDirection !== undefined)
            url_ += "sortDirection=" + encodeURIComponent("" + sortDirection) + "&";
        if (isDownloadAll === null)
            throw new Error("The parameter 'isDownloadAll' cannot be null.");
        else if (isDownloadAll !== undefined)
            url_ += "isDownloadAll=" + encodeURIComponent("" + isDownloadAll) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            signal,
            headers: {
                "Accept": "text/plain"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processListCompaniesCursor(_response);
        });
    }

    protected processListCompaniesCursor(response: Response): Promise<CompaniesResponseCursor> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = CompaniesResponseCursor.fromJS(resultData200);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<CompaniesResponseCursor>(null as any);
    }

    /**
     * @return OK
     */
    deleteCompany(id: number, signal?: AbortSignal): Promise<void> {
        let url_ = this.baseUrl + "/api/v2/companies/{id}";
        if (id === undefined || id === null)
            throw new Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "DELETE",
            signal,
            headers: {
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processDeleteCompany(_response);
        });
    }

    protected processDeleteCompany(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * Applies a JSON Patch to a company.
     * @param body (optional) 
     * @return OK
     */
    patchCompany(id: number, body?: Operation[] | undefined, signal?: AbortSignal): Promise<CompanyDto> {
        let url_ = this.baseUrl + "/api/v2/companies/{id}";
        if (id === undefined || id === null)
            throw new Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "PATCH",
            signal,
            headers: {
                "Content-Type": "application/json-patch+json",
                "Accept": "text/plain"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processPatchCompany(_response);
        });
    }

    protected processPatchCompany(response: Response): Promise<CompanyDto> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = CompanyDto.fromJS(resultData200);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<CompanyDto>(null as any);
    }

    /**
     * @return OK
     */
    getCompany(id: number, signal?: AbortSignal): Promise<CompanyDto> {
        let url_ = this.baseUrl + "/api/v2/companies/{id}";
        if (id === undefined || id === null)
            throw new Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            signal,
            headers: {
                "Accept": "text/plain"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGetCompany(_response);
        });
    }

    protected processGetCompany(response: Response): Promise<CompanyDto> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = CompanyDto.fromJS(resultData200);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<CompanyDto>(null as any);
    }

    /**
     * @return OK
     */
    getCompanyContacts(companyId: number, signal?: AbortSignal): Promise<ContactDto[]> {
        let url_ = this.baseUrl + "/api/v2/companies/{companyId}/contacts";
        if (companyId === undefined || companyId === null)
            throw new Error("The parameter 'companyId' must be defined.");
        url_ = url_.replace("{companyId}", encodeURIComponent("" + companyId));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "GET",
            signal,
            headers: {
                "Accept": "text/plain"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processGetCompanyContacts(_response);
        });
    }

    protected processGetCompanyContacts(response: Response): Promise<ContactDto[]> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            if (Array.isArray(resultData200)) {
                result200 = [] as any;
                for (let item of resultData200)
                    result200!.push(ContactDto.fromJS(item));
            }
            else {
                result200 = <any>null;
            }
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<ContactDto[]>(null as any);
    }

    /**
     * @param body (optional) 
     * @return OK
     */
    createCompanyContact(companyId: number, body?: CreateContactDto | undefined, signal?: AbortSignal): Promise<ContactDto> {
        let url_ = this.baseUrl + "/api/v2/companies/{companyId}/contacts";
        if (companyId === undefined || companyId === null)
            throw new Error("The parameter 'companyId' must be defined.");
        url_ = url_.replace("{companyId}", encodeURIComponent("" + companyId));
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "POST",
            signal,
            headers: {
                "Content-Type": "application/json-patch+json",
                "Accept": "text/plain"
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processCreateCompanyContact(_response);
        });
    }

    protected processCreateCompanyContact(response: Response): Promise<ContactDto> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            let result200: any = null;
            let resultData200 = _responseText === "" ? null : JSON.parse(_responseText, this.jsonParseReviver);
            result200 = ContactDto.fromJS(resultData200);
            return result200;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<ContactDto>(null as any);
    }

    /**
     * @return OK
     */
    deleteContact(companyId: number, id: number, signal?: AbortSignal): Promise<void> {
        let url_ = this.baseUrl + "/api/v2/companies/{companyId}/contacts/{id}";
        if (companyId === undefined || companyId === null)
            throw new Error("The parameter 'companyId' must be defined.");
        url_ = url_.replace("{companyId}", encodeURIComponent("" + companyId));
        if (id === undefined || id === null)
            throw new Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        let options_: RequestInit = {
            method: "DELETE",
            signal,
            headers: {
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processDeleteContact(_response);
        });
    }

    protected processDeleteContact(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }

    /**
     * @param body (optional) 
     * @return OK
     */
    updateContact(companyId: number, id: number, body?: ContactDto | undefined, signal?: AbortSignal): Promise<void> {
        let url_ = this.baseUrl + "/api/v2/companies/{companyId}/contacts/{id}";
        if (companyId === undefined || companyId === null)
            throw new Error("The parameter 'companyId' must be defined.");
        url_ = url_.replace("{companyId}", encodeURIComponent("" + companyId));
        if (id === undefined || id === null)
            throw new Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: RequestInit = {
            body: content_,
            method: "PUT",
            signal,
            headers: {
                "Content-Type": "application/json-patch+json",
            }
        };

        return this.http.fetch(url_, options_).then((_response: Response) => {
            return this.processUpdateContact(_response);
        });
    }

    protected processUpdateContact(response: Response): Promise<void> {
        const status = response.status;
        let _headers: any = {}; if (response.headers && response.headers.forEach) { response.headers.forEach((v: any, k: any) => _headers[k] = v); };
        if (status === 200) {
            return response.text().then((_responseText) => {
            return;
            });
        } else if (status !== 200 && status !== 204) {
            return response.text().then((_responseText) => {
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
            });
        }
        return Promise.resolve<void>(null as any);
    }
}

export enum CompClassificationDto {
    Unspecified = "Unspecified",
    GoodMatch = "GoodMatch",
    Maybe = "Maybe",
    Ecommerce = "Ecommerce",
    GimmeSomeLove = "GimmeSomeLove",
}

export class CompaniesResponseCursor implements ICompaniesResponseCursor {
    companies?: CompanyDto[] | undefined;
    pagination?: PaginationCursorDto;

    constructor(data?: ICompaniesResponseCursor) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            if (Array.isArray(_data["companies"])) {
                this.companies = [] as any;
                for (let item of _data["companies"])
                    this.companies!.push(CompanyDto.fromJS(item));
            }
            this.pagination = _data["pagination"] ? PaginationCursorDto.fromJS(_data["pagination"]) : <any>undefined;
        }
    }

    static fromJS(data: any): CompaniesResponseCursor {
        data = typeof data === 'object' ? data : {};
        let result = new CompaniesResponseCursor();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        if (Array.isArray(this.companies)) {
            data["companies"] = [];
            for (let item of this.companies)
                data["companies"].push(item ? item.toJSON() : <any>undefined);
        }
        data["pagination"] = this.pagination ? this.pagination.toJSON() : <any>undefined;
        return data;
    }

    clone(): CompaniesResponseCursor {
        const json = this.toJSON();
        let result = new CompaniesResponseCursor();
        result.init(json);
        return result;
    }
}

export interface ICompaniesResponseCursor {
    companies?: CompanyDto[] | undefined;
    pagination?: PaginationCursorDto;
}

export class CompaniesResponseOffset implements ICompaniesResponseOffset {
    companies?: CompanyDto[] | undefined;
    pagination?: PaginationDto;

    constructor(data?: ICompaniesResponseOffset) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            if (Array.isArray(_data["companies"])) {
                this.companies = [] as any;
                for (let item of _data["companies"])
                    this.companies!.push(CompanyDto.fromJS(item));
            }
            this.pagination = _data["pagination"] ? PaginationDto.fromJS(_data["pagination"]) : <any>undefined;
        }
    }

    static fromJS(data: any): CompaniesResponseOffset {
        data = typeof data === 'object' ? data : {};
        let result = new CompaniesResponseOffset();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        if (Array.isArray(this.companies)) {
            data["companies"] = [];
            for (let item of this.companies)
                data["companies"].push(item ? item.toJSON() : <any>undefined);
        }
        data["pagination"] = this.pagination ? this.pagination.toJSON() : <any>undefined;
        return data;
    }

    clone(): CompaniesResponseOffset {
        const json = this.toJSON();
        let result = new CompaniesResponseOffset();
        result.init(json);
        return result;
    }
}

export interface ICompaniesResponseOffset {
    companies?: CompanyDto[] | undefined;
    pagination?: PaginationDto;
}

export class CompanyDto implements ICompanyDto {
    id?: number;
    companyName?: string | undefined;
    country?: string | undefined;
    city?: string | undefined;
    fullAddress?: string | undefined;
    website?: string | undefined;
    categoryGoogle?: string | undefined;
    ratingGoogle?: number | undefined;
    ratedCount?: string | undefined;
    googleMapsUrl?: string | undefined;
    bigFishScore?: number | undefined;
    classification?: CompClassificationDto[] | undefined;
    markdownNote?: string | undefined;

    constructor(data?: ICompanyDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.companyName = _data["companyName"];
            this.country = _data["country"];
            this.city = _data["city"];
            this.fullAddress = _data["fullAddress"];
            this.website = _data["website"];
            this.categoryGoogle = _data["categoryGoogle"];
            this.ratingGoogle = _data["ratingGoogle"];
            this.ratedCount = _data["ratedCount"];
            this.googleMapsUrl = _data["googleMapsUrl"];
            this.bigFishScore = _data["bigFishScore"];
            if (Array.isArray(_data["classification"])) {
                this.classification = [] as any;
                for (let item of _data["classification"])
                    this.classification!.push(item);
            }
            this.markdownNote = _data["markdownNote"];
        }
    }

    static fromJS(data: any): CompanyDto {
        data = typeof data === 'object' ? data : {};
        let result = new CompanyDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["companyName"] = this.companyName;
        data["country"] = this.country;
        data["city"] = this.city;
        data["fullAddress"] = this.fullAddress;
        data["website"] = this.website;
        data["categoryGoogle"] = this.categoryGoogle;
        data["ratingGoogle"] = this.ratingGoogle;
        data["ratedCount"] = this.ratedCount;
        data["googleMapsUrl"] = this.googleMapsUrl;
        data["bigFishScore"] = this.bigFishScore;
        if (Array.isArray(this.classification)) {
            data["classification"] = [];
            for (let item of this.classification)
                data["classification"].push(item);
        }
        data["markdownNote"] = this.markdownNote;
        return data;
    }

    clone(): CompanyDto {
        const json = this.toJSON();
        let result = new CompanyDto();
        result.init(json);
        return result;
    }
}

export interface ICompanyDto {
    id?: number;
    companyName?: string | undefined;
    country?: string | undefined;
    city?: string | undefined;
    fullAddress?: string | undefined;
    website?: string | undefined;
    categoryGoogle?: string | undefined;
    ratingGoogle?: number | undefined;
    ratedCount?: string | undefined;
    googleMapsUrl?: string | undefined;
    bigFishScore?: number | undefined;
    classification?: CompClassificationDto[] | undefined;
    markdownNote?: string | undefined;
}

export class ContactDto implements IContactDto {
    id?: number;
    companyId?: number;
    value!: string | undefined;
    type?: ContactTypeDto;
    isOnWhatsapp?: boolean | undefined;
    contactedFromEmail?: string | undefined;
    checked?: boolean | undefined;
    date?: Date | undefined;

    constructor(data?: IContactDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.companyId = _data["companyId"];
            this.value = _data["value"];
            this.type = _data["type"];
            this.isOnWhatsapp = _data["isOnWhatsapp"];
            this.contactedFromEmail = _data["contactedFromEmail"];
            this.checked = _data["checked"];
            this.date = _data["date"] ? new Date(_data["date"].toString()) : <any>undefined;
        }
    }

    static fromJS(data: any): ContactDto {
        data = typeof data === 'object' ? data : {};
        let result = new ContactDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["companyId"] = this.companyId;
        data["value"] = this.value;
        data["type"] = this.type;
        data["isOnWhatsapp"] = this.isOnWhatsapp;
        data["contactedFromEmail"] = this.contactedFromEmail;
        data["checked"] = this.checked;
        data["date"] = this.date ? this.date.toISOString() : <any>undefined;
        return data;
    }

    clone(): ContactDto {
        const json = this.toJSON();
        let result = new ContactDto();
        result.init(json);
        return result;
    }
}

export interface IContactDto {
    id?: number;
    companyId?: number;
    value: string | undefined;
    type?: ContactTypeDto;
    isOnWhatsapp?: boolean | undefined;
    contactedFromEmail?: string | undefined;
    checked?: boolean | undefined;
    date?: Date | undefined;
}

export enum ContactTypeDto {
    Unspecified = "Unspecified",
    Email = "Email",
    PhoneNumber = "PhoneNumber",
    Facebook = "Facebook",
    Instagram = "Instagram",
    LinkedIn = "LinkedIn",
    Other = "Other",
}

export class CreateContactDto implements ICreateContactDto {
    companyId?: number;
    value!: string | undefined;
    type?: ContactTypeDto;

    constructor(data?: ICreateContactDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.companyId = _data["companyId"];
            this.value = _data["value"];
            this.type = _data["type"];
        }
    }

    static fromJS(data: any): CreateContactDto {
        data = typeof data === 'object' ? data : {};
        let result = new CreateContactDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["companyId"] = this.companyId;
        data["value"] = this.value;
        data["type"] = this.type;
        return data;
    }

    clone(): CreateContactDto {
        const json = this.toJSON();
        let result = new CreateContactDto();
        result.init(json);
        return result;
    }
}

export interface ICreateContactDto {
    companyId?: number;
    value: string | undefined;
    type?: ContactTypeDto;
}

export class Operation implements IOperation {
    operationType?: OperationType;
    path?: string | undefined;
    op?: string | undefined;
    from?: string | undefined;
    value?: any | undefined;

    constructor(data?: IOperation) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.operationType = _data["operationType"];
            this.path = _data["path"];
            this.op = _data["op"];
            this.from = _data["from"];
            this.value = _data["value"];
        }
    }

    static fromJS(data: any): Operation {
        data = typeof data === 'object' ? data : {};
        let result = new Operation();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["operationType"] = this.operationType;
        data["path"] = this.path;
        data["op"] = this.op;
        data["from"] = this.from;
        data["value"] = this.value;
        return data;
    }

    clone(): Operation {
        const json = this.toJSON();
        let result = new Operation();
        result.init(json);
        return result;
    }
}

export interface IOperation {
    operationType?: OperationType;
    path?: string | undefined;
    op?: string | undefined;
    from?: string | undefined;
    value?: any | undefined;
}

export enum OperationType {
    Add = "Add",
    Remove = "Remove",
    Replace = "Replace",
    Move = "Move",
    Copy = "Copy",
    Test = "Test",
    Invalid = "Invalid",
}

export class PaginationCursorDto implements IPaginationCursorDto {
    totalCount?: number;
    nextCursor?: string | undefined;

    constructor(data?: IPaginationCursorDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.totalCount = _data["totalCount"];
            this.nextCursor = _data["nextCursor"];
        }
    }

    static fromJS(data: any): PaginationCursorDto {
        data = typeof data === 'object' ? data : {};
        let result = new PaginationCursorDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["totalCount"] = this.totalCount;
        data["nextCursor"] = this.nextCursor;
        return data;
    }

    clone(): PaginationCursorDto {
        const json = this.toJSON();
        let result = new PaginationCursorDto();
        result.init(json);
        return result;
    }
}

export interface IPaginationCursorDto {
    totalCount?: number;
    nextCursor?: string | undefined;
}

export class PaginationDto implements IPaginationDto {
    totalCount?: number;
    pageIndex?: number;
    pageSize?: number;

    constructor(data?: IPaginationDto) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (<any>this)[property] = (<any>data)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.totalCount = _data["totalCount"];
            this.pageIndex = _data["pageIndex"];
            this.pageSize = _data["pageSize"];
        }
    }

    static fromJS(data: any): PaginationDto {
        data = typeof data === 'object' ? data : {};
        let result = new PaginationDto();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["totalCount"] = this.totalCount;
        data["pageIndex"] = this.pageIndex;
        data["pageSize"] = this.pageSize;
        return data;
    }

    clone(): PaginationDto {
        const json = this.toJSON();
        let result = new PaginationDto();
        result.init(json);
        return result;
    }
}

export interface IPaginationDto {
    totalCount?: number;
    pageIndex?: number;
    pageSize?: number;
}

export class SwaggerException extends Error {
    message: string;
    status: number;
    response: string;
    headers: { [key: string]: any; };
    result: any;

    constructor(message: string, status: number, response: string, headers: { [key: string]: any; }, result: any) {
        super();

        this.message = message;
        this.status = status;
        this.response = response;
        this.headers = headers;
        this.result = result;
    }

    protected isSwaggerException = true;

    static isSwaggerException(obj: any): obj is SwaggerException {
        return obj.isSwaggerException === true;
    }
}

function throwException(message: string, status: number, response: string, headers: { [key: string]: any; }, result?: any): any {
    if (result !== null && result !== undefined)
        throw result;
    else
        throw new SwaggerException(message, status, response, headers, null);
}